[package]
name = "mctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
tempfile = "3.3.0"
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
